@startuml
'https://plantuml.com/ja/state-diagram

<style>
stateDiagram {
  arrow {
    FontSize 10
  }
}
</style>

[*] --> BattleStartState
BattleStartState --> InitializeEnemyState
InitializeEnemyState --> TurnState
TurnState --> TurnState
TurnState --> BattleStopState
BattleStopState --> [*]
@enduml