@startuml
'https://plantuml.com/class-diagram

package Model{
    package Domain{
        enum Enum
        class Id
        class Entity
        class ValueObject
        class DomainService
        interface IRepository
        interface IReadonlyRepository
        interface IFactory
        Enum <-- Entity
        Id <-- Entity
        Enum <-- ValueObject
        IRepository <-- DomainService
        IReadonlyRepository <-- DomainService
    }
    
    package UseCases{
        class Service
    
        Domain <-- Service
        Entity <-- IRepository
        ValueObject <-- IFactory
    }
    
    package DataAccess{
        class Repository
        class Factory
        IRepository <|-- Repository
        IReadonlyRepository <|-- Repository
        IFactory <|-- Factory
    }
}

package Presenter{
    class ViewModelService
}

package View{
}





@enduml