@startuml
'https://plantuml.com/class-diagram

package Model{
    package DataAccess{
        class Collection
        class Factory
        interface IResource
        class Resource
        Resource --|> IResource
    }

    package UseCases{
        class Service
        class UseCase
        interface ICollection
        interface IFactory
        interface IService
        ICollection <-- Service
        IFactory <-- Service
        IService <|-- Service
        IService <-- UseCase
    }

    package Domain{
        class Entity
        class ValueObject
        ValueObject <-l- Entity
    }

    ICollection ---> Entity
    IFactory ---> ValueObject
    Collection ---|> ICollection
    Factory ---|> IFactory
}

package Presenters{
    class State
    class Context
    class StateMachine
    class Facade
    class Presenter
    UseCase <-- State
    Facade <-- State
    Presenter <-- Facade
    State <-- Context
    Context <-- StateMachine
}

package Views{
    class View
    class ViewModel
    ViewModel <- View
}

IResource <-- Presenter
View <-- Presenter
ViewModel <-- Presenter

@enduml