@startuml
class OrderedItemEntity {
    + OrderedItemId OrderedItemId
    + OrderNumber OrderNumber
}

class OrderedCharacterEntity {
    + OrderedCharacterId OrderedCharacterId
    + CharacterId CharacterId
    + IOrderedItemId GetOrderedItemId()
}

OrderedItemEntity "1..*" -- "0..*" OrderedCharacterEntity 
@enduml