@startuml
'https://plantuml.com/ja/state-diagram

<style>
stateDiagram {
  arrow {
    FontSize 10
  }
}
</style>

[*] --> PrimeSkillStartState
PrimeSkillStartState --> PrimeSkillStopState : プレイヤーに対し状態異常を失敗
PrimeSkillStartState -> PrimeSkillOutputState
PrimeSkillOutputState --> PrimeSkillOutputState : 表示するメッセージが残っている
PrimeSkillOutputState --> PrimeSkillStopState : すべてのメッセージを表示した
PrimeSkillStopState --> [*]

PrimeSkillStartState : スキルを実行した結果を\nCollectionに登録
PrimeSkillOutputState : スキルを実行した結果を\n画面に表示
PrimeSkillStopState : スキルの実行を終了する
@enduml