@startuml
'https://plantuml.com/sequence-diagram

autonumber
SkillState -> StateMachine: Select()
note left: Skillインスタンスを渡し、\nステートをスタートさせる
StateMachine -> Context: Create
note left: Skillインスタンスを渡し、\nContextインスタンスを生成する
activate Context
Context -> SkillStartState: TransitionTo()
Context -> SkillStartState: SkillList
note left: Skillインスタンスのリストを渡す
SkillStartState -> SkillUseCase: GetBattleEventList()
note left: Skillインスタンスのリストを渡し、\nBattleEventインスタンスのリストを要求する
SkillUseCase -> SkillService: GenerateBattleEvent()
SkillService --> SkillUseCase: battleEventList
note left: Skillインスタンスのリストをもとに生成した\nBattleEventインスタンスのリストを返す
SkillUseCase --> SkillStartState: battleEventList
SkillStartState -> SkillUseCase: RegisterBattleEvent()
note left: BattleEventインスタンスのリストを渡し、\nRepositoryの更新を要求する
SkillUseCase -> BattleLoggerService: Log()
note left: BattleEventインスタンスからBattleLogインスタンスを生成し、\nRepositoryに登録する
BattleLoggerService -> Repository: Update()
SkillUseCase -> SkillService: RegisterBattleEvent()
note left: BattleEventインスタンスをもとに各種Repositoryを更新する
SkillService -> Repository: Update()
SkillStartState --> Context: BattleEventQueue
note left: BattleEventインスタンスのリストを\nキューに変換して返す
@enduml