@startuml
start
switch()
    case(行動不能)
        :AilmentState]
        if() then (yes)
            :AilmentMessageState]
        else (no)
            :AilmentFailureState]
        endif
        :SkillEndState]
    case(スリップ)
        :SlipState]
stop
@enduml