@startuml
'https://plantuml.com/ja/state-diagram

<style>
stateDiagram {
  arrow {
    FontSize 10
  }
}
</style>

[*] --> SkillElementStartState
SkillElementStartState --> SkillElementStopState : プレイヤーに対し状態異常を失敗
SkillElementStartState -> SkillElementOutputState
SkillElementOutputState --> SkillElementOutputState : 表示するメッセージが残っている
SkillElementOutputState --> SkillElementStopState : すべてのメッセージを表示した
SkillElementStopState --> [*]

SkillElementStartState : スキルを実行した結果を\nCollectionに登録
SkillElementOutputState : スキルを実行した結果を\n画面に表示
SkillElementStopState : スキルの実行を終了する
@enduml