using BattleScene.Domain.DomainService;
using BattleScene.UseCase.BusinessLogic;
using BattleScene.UseCase.Event;
using BattleScene.UseCase.Event.Runner;
using BattleScene.UseCase.Main;
using BattleScene.UseCase.Service;
using BattleScene.UseCase.Skill;
using BattleScene.UseCase.Skill.Expression;
using BattleScene.UseCase.Skill.SkillElement;
using BattleScene.UseCase.View.AilmentView;
using BattleScene.UseCase.View.AilmentView.OutputDataFactory;
using BattleScene.UseCase.View.AttackCountView.OutputDataFactory;
using BattleScene.UseCase.View.BuffView.OutputDataFactory;
using BattleScene.UseCase.View.CharacterVibesView.OutputDataFactory;
using BattleScene.UseCase.View.DestroyedPartView.OutputDataFactory;
using BattleScene.UseCase.View.DigitView.OutputDataFactory;
using BattleScene.UseCase.View.EnemyView.OutputDataFactory;
using BattleScene.UseCase.View.FrameView.OutputDataFactory;
using BattleScene.UseCase.View.HitPointBarView.OutputDataFactory;
using BattleScene.UseCase.View.IsContinueView.OutputDataFactory;
using BattleScene.UseCase.View.MessageView.OutputDataFactory;
using BattleScene.UseCase.View.OrderView;
using BattleScene.UseCase.View.OrderView.OutputDataFactory;
using BattleScene.UseCase.View.PlayerImageView.OutputDataFactory;
using BattleScene.UseCase.View.SelectActionView.OutputDataFactory;
using BattleScene.UseCase.View.SelectSkillView.OutputDataFactory;
using BattleScene.UseCase.View.TechnicalPointBarView.OutputDaraFactory;
using VContainer;
using VContainer.Unity;

namespace BattleScene.UseCase
{
    public class BattleSceneUseCaseLifetimeScope : LifetimeScope
    {
        protected override void Configure(IContainerBuilder builder)
        {
            builder.Register<AilmentSkillEvent>(Lifetime.Singleton);
            builder.Register<AilmentsResetEvent>(Lifetime.Singleton);
            builder.Register<SlipDamageEvent>(Lifetime.Singleton);
            builder.Register<SlipDamageMessageEvent>(Lifetime.Singleton);
            builder.Register<BattleStartLogic>(Lifetime.Singleton);
            builder.Register<BuffEvent>(Lifetime.Singleton);
            builder.Register<CantActionEvent>(Lifetime.Singleton);
            builder.Register<CureEvent>(Lifetime.Singleton);
            builder.Register<DestroyedPartEvent>(Lifetime.Singleton);
            builder.Register<EnemySelectSkillLogic>(Lifetime.Singleton);
            builder.Register<EnemySuicideEvent>(Lifetime.Singleton);
            builder.Register<InitializationLogic>(Lifetime.Singleton);
            builder.Register<IsContinueEvent>(Lifetime.Singleton);
            builder.Register<LoopEndEvent>(Lifetime.Singleton);
            builder.Register<OrderDecisionLogic>(Lifetime.Singleton);
            builder.Register<PlayerAttackEvent>(Lifetime.Singleton);
            builder.Register<PlayerBeatEnemyEvent>(Lifetime.Singleton);
            builder.Register<PlayerDeadEvent>(Lifetime.Singleton);
            builder.Register<PlayerDamageEvent>(Lifetime.Singleton);
            builder.Register<PlayerWinEvent>(Lifetime.Singleton);
            builder.Register<ResetSkillEvent>(Lifetime.Singleton);
            builder.Register<SelectActionEvent>(Lifetime.Singleton);
            builder.Register<SelectFatalitySkillEvent>(Lifetime.Singleton);
            builder.Register<SelectSkillEvent>(Lifetime.Singleton);
            builder.Register<SelectTargetEvent>(Lifetime.Singleton);
            builder.Register<Runner>(Lifetime.Singleton);
            builder.Register<UseCaseFactory>(Lifetime.Singleton);
            builder.Register<OutputFactory>(Lifetime.Singleton);
            builder.Register<IEventFactory, EventFactory>(Lifetime.Singleton);
            builder.Register<ActionTimeCreatorService>(Lifetime.Singleton);
            builder.Register<AgilityToSpeedService>(Lifetime.Singleton);
            builder.Register<AilmentSkillService>(Lifetime.Singleton);
            builder.Register<AttackCounterService>(Lifetime.Singleton);
            builder.Register<CharacterCreatorService>(Lifetime.Singleton);
            builder.Register<CharacterOutputDataCreatorService>(Lifetime.Singleton);
            builder.Register<CureSkillService>(Lifetime.Singleton);
            builder.Register<DamageSkillService>(Lifetime.Singleton);
            builder.Register<DestroyedPartCreatorService>(Lifetime.Singleton);
            builder.Register<OrderedItemCreatorService>(Lifetime.Singleton);
            builder.Register<ResetSkillService>(Lifetime.Singleton);
            builder.Register<SelectSkillService>(Lifetime.Singleton);
            builder.Register<SkillCreatorService>(Lifetime.Singleton);
            builder.Register<SkillService>(Lifetime.Singleton);
            builder.Register<SlipDamageService>(Lifetime.Singleton);
            builder.Register<ToBodyPartNumberService>(Lifetime.Singleton);
            builder.Register<ToBuffNumberService>(Lifetime.Singleton);
            builder.Register<TurnService>(Lifetime.Singleton);

            builder.Register<AilmentDomainService>(Lifetime.Singleton);
            builder.Register<BodyPartDomainService>(Lifetime.Singleton);
            builder.Register<BuffDomainService>(Lifetime.Singleton);
            builder.Register<CharactersDomainService>(Lifetime.Singleton);
            builder.Register<HitPointDomainService>(Lifetime.Singleton);
            builder.Register<OrderedItemsDomainService>(Lifetime.Singleton);
            builder.Register<ResultCreatorDomainService>(Lifetime.Singleton);
            builder.Register<ResultDomainService>(Lifetime.Singleton);
            builder.Register<SlipDamageDomainService>(Lifetime.Singleton);
            builder.Register<TargetDomainService>(Lifetime.Singleton);

            builder.Register<AilmentOutputDataFactory>(Lifetime.Singleton);
            builder.Register<AttackCountOutputDataFactory>(Lifetime.Singleton);
            builder.Register<BuffOutputDataFactory>(Lifetime.Singleton);
            builder.Register<CharacterVibesOutputDataFactory>(Lifetime.Singleton);
            builder.Register<DestroyedPartOutputDataFactory>(Lifetime.Singleton);
            builder.Register<CureDigitOutputDataFactory>(Lifetime.Singleton);
            builder.Register<DamageDigitOutputDataFactory>(Lifetime.Singleton);
            builder.Register<EnemyOutputDataFactory>(Lifetime.Singleton);
            builder.Register<TargetFrameOutputDataFactory>(Lifetime.Singleton);
            builder.Register<HitPointBarOutputDataFactory>(Lifetime.Singleton);
            builder.Register<IsContinueOutputDataFactory>(Lifetime.Singleton);
            builder.Register<AilmentMessageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<DamageMessageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<MessageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<SelectSkillMessageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<OrderOutputDataFactory>(Lifetime.Singleton);
            builder.Register<AilmentPlayerImageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<PlayerAttackPlayerImageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<PlayerImageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<SelectSkillPlayerImageOutputDataFactory>(Lifetime.Singleton);
            builder.Register<SelectActionOutputDataFactory>(Lifetime.Singleton);
            builder.Register<SelectSkillOutputDataFactory>(Lifetime.Singleton);
            builder.Register<TechnicalPointBarOutputDataFactory>(Lifetime.Singleton);
            
            builder.Register<AfterimageSkill>(Lifetime.Singleton);
            builder.Register<AttackSkill>(Lifetime.Singleton);
            builder.Register<BiteSkill>(Lifetime.Singleton);
            builder.Register<BiteOffSkill>(Lifetime.Singleton);
            builder.Register<ConfusionSkill>(Lifetime.Singleton);
            builder.Register<CutUpSkill>(Lifetime.Singleton);
            builder.Register<DefenceSkill>(Lifetime.Singleton);
            builder.Register<FieldRationSkill>(Lifetime.Singleton);
            builder.Register<FirstAidSkill>(Lifetime.Singleton);
            builder.Register<FlameThrowSkill>(Lifetime.Singleton);
            builder.Register<HonzougakuSkill>(Lifetime.Singleton);
            builder.Register<IshinhouSkill>(Lifetime.Singleton);
            builder.Register<KuchiyoseSkill>(Lifetime.Singleton);
            builder.Register<KyoukasuigetsuSkill>(Lifetime.Singleton);
            builder.Register<LiquidSkill>(Lifetime.Singleton);
            builder.Register<MurasameSkill>(Lifetime.Singleton);
            builder.Register<MusterStrengthSkill>(Lifetime.Singleton);
            builder.Register<NadegiriSkill>(Lifetime.Singleton);
            builder.Register<NumbLiquidSkill>(Lifetime.Singleton);
            builder.Register<OnikoroshiSkill>(Lifetime.Singleton);
            builder.Register<PunchSkill>(Lifetime.Singleton);
            builder.Register<PutScytheSkill>(Lifetime.Singleton);
            builder.Register<RaikiriSkill>(Lifetime.Singleton);
            builder.Register<RandomShotsSkill>(Lifetime.Singleton);
            builder.Register<ShichishitouSkill>(Lifetime.Singleton);
            builder.Register<SilverBulletSkill>(Lifetime.Singleton);
            builder.Register<SmokeBombSkill>(Lifetime.Singleton);
            builder.Register<StarShellSkill>(Lifetime.Singleton);
            builder.Register<StringerSkill>(Lifetime.Singleton);
            builder.Register<TaserGunSkill>(Lifetime.Singleton);
            builder.Register<UtsusemiSkill>(Lifetime.Singleton);
            builder.Register<WabisukeSkill>(Lifetime.Singleton);

            builder.Register<AbsoluteConfusionSkillElement>(Lifetime.Singleton);
            builder.Register<AfterImageSkillElement>(Lifetime.Singleton);
            builder.Register<AlwaysHitDamageSkillElement>(Lifetime.Singleton);
            builder.Register<BasicCureSkillElement>(Lifetime.Singleton);
            builder.Register<BasicDamageSkillElement>(Lifetime.Singleton);
            builder.Register<BasicRestoreTechnicalPointSkillElement>(Lifetime.Singleton);
            builder.Register<BleedingSkillElement>(Lifetime.Singleton);
            builder.Register<BlindSkillElement>(Lifetime.Singleton);
            builder.Register<BurningResetSkillElement>(Lifetime.Singleton);
            builder.Register<BurningSkillElement>(Lifetime.Singleton);
            builder.Register<ConfusionSkillElement>(Lifetime.Singleton);
            builder.Register<ConstantDamageSkillElement>(Lifetime.Singleton);
            builder.Register<DefenceSkillElement>(Lifetime.Singleton);
            builder.Register<DestroyArmSkillElement>(Lifetime.Singleton);
            builder.Register<DestroyLegSkillElement>(Lifetime.Singleton);
            builder.Register<DestroyStomachSkillElement>(Lifetime.Singleton);
            builder.Register<EnemyParalysisSkillElement>(Lifetime.Singleton);
            builder.Register<FirstAidSkillElement>(Lifetime.Singleton);
            builder.Register<FiveTimeDamageSkillElement>(Lifetime.Singleton);
            builder.Register<HonzougakuSkillElement>(Lifetime.Singleton);
            builder.Register<IshinhouSkillElement>(Lifetime.Singleton);
            builder.Register<LightningDamageSkillElement>(Lifetime.Singleton);
            builder.Register<MusterStrengthSkillElement>(Lifetime.Singleton);
            builder.Register<NadegiriSkillElement>(Lifetime.Singleton);
            builder.Register<ParalysisSkillElement>(Lifetime.Singleton);
            builder.Register<PoisoningSkillElement>(Lifetime.Singleton);
            builder.Register<RandomShotSkillElement>(Lifetime.Singleton);
            builder.Register<ShichishitouSkillElement>(Lifetime.Singleton);
            builder.Register<StarShellSkillElement>(Lifetime.Singleton);
            builder.Register<SuffocationSkillElement>(Lifetime.Singleton);
            builder.Register<UtsusemiSkillElement>(Lifetime.Singleton);
            builder.Register<WabisukeSkillElement>(Lifetime.Singleton);
            
            builder.Register<AttacksWeakPointEvaluation>(Lifetime.Singleton);
            builder.Register<ConstantDamageExpression>(Lifetime.Singleton);
            builder.Register<CureExpression>(Lifetime.Singleton);
            builder.Register<DamageExpression>(Lifetime.Singleton);
            builder.Register<HitEvaluation>(Lifetime.Singleton);
            builder.Register<Luck>(Lifetime.Singleton);

            builder.Register<AilmentViewOutput>(Lifetime.Singleton);
            builder.Register<OrderViewOutput>(Lifetime.Singleton);

            builder.Register<StateMachine>(Lifetime.Singleton);
            builder.Register<StateFactory>(Lifetime.Singleton);
            builder.Register<InitializeStateFactory>(Lifetime.Singleton);
            builder.Register<EnemySkillStateFactory>(Lifetime.Singleton);
        }
    }
}