namespace BattleScene.Domain.Code
{
    public enum MessageCode
    {
        NoMessage, //  (メッセージ未設定)
        AfterimageMessage, // 敵行動 (残像)
        AilmentMessage, // 共通 (状態異常)
        AttackDescription, // スキル説明 (ATTACK)
        AttackMessage, // 共通 (攻撃)
        AvoidMessage, // 共通 (回避)
        BeatEnemyMessage, // 共通 (敵死亡)
        BiteArmMessage, // 敵行動 (噛みつき)
        BiteLegMessage, // 敵行動 (噛みつき)
        BiteOffArmMessage, // 敵行動 (食いちぎり)
        BiteOffLegMessage, // 敵行動 (食いちぎり)
        BiteOffStomachMessage, // 敵行動 (食いちぎり)
        BiteStomachMessage, // 敵行動 (噛みつき)
        BleedingMessage, // スリップ (出血)
        BuffMessage, // 共通 (バフ)
        BurningMessage, // スリップ (燃焼)
        CureMessage, // 共通 (HP回復)
        CutArmMessage, // 敵行動 (命を刈る鎌)
        CutLegMessage, // 敵行動 (命を刈る鎌)
        CutStomachMessage, // 敵行動 (命を刈る鎌)
        CutUpArmMessage, // 敵行動 (切り刻み)
        CutUpLegMessage, // 敵行動 (切り刻み)
        CutUpStomachMessage, // 敵行動 (切り刻み)
        DamageMessage, // 共通 (与ダメージ)
        DamageOneselfMessage, // 共通 (自身に与ダメージ)
        DebuffMessage, // 共通 (デバフ)
        DefenceDescription, // スキル説明 (DEFENCE)
        DefenceActionMessage, // 共通 (防御)
        EnemyConfusionActMessage, // 状態異常 (敵混乱)
        EnemySuicideMessage, // 共通 (敵自滅)
        FailAilmentMessage, // 共通 (状態異常失敗)
        FatalitySkillDescription, // スキル説明 (FATALITY)
        FieldRationDescription, // スキル説明 (レーション)
        FirstAidDescription, // スキル説明 (ファーストエイド)
        FrameThrowMessage, // 敵行動 (火炎放射)
        HonzougakuDescription, // スキル説明 (本草学)
        InvasiveMouthMessage, // 敵行動 (粘液)
        IsContinueMessage, // 共通 (継続)
        IshinhouDescription, // スキル説明 (医心方)
        KuchiyoseDescription, // スキル説明 (口寄せ)
        KyoukasuigetsuDescription, // スキル説明 (鏡花水月)
        MurasameDescription, // スキル説明 (村雨)
        MusterStrengthDescription, // スキル説明 (力溜め)
        NadegiriDescription, // スキル説明 (撫斬)
        NumbLiquidMessage, // 敵行動 (痺れる粘液)
        OnikoroshiMessage, // 敵行動 (鬼殺し)
        ParalysisCantActMessage, // 状態異常 (麻痺)
        PlayerConfusionActMessage, // 状態異常 (プレイヤー混乱)
        PlayerDeadMessage, // 共通 (死亡)
        PlayerWinMessage, // 共通 (勝利)
        PoisoningMessage, // スリップ (中毒)
        PunchStomachMessage, // 敵行動 (殴りつけ)
        RaikiriDescription, // スキル説明 (雷切)
        RandomShotsDescription, // スキル説明 (ランダムショット)
        RecoverAilmentMessage, // 共通 (状態異常回復)
        RecoverPartMessage, // 共通 (損傷部位回復)
        RecoverSlipMessage, // 共通 (状態異常回復)
        ResetAilmentMessage, // 共通 (状態異常解除)
        RestoreMessage, // 共通 (TP回復)
        SelectTargetMessage, // 共通 (敵選択)
        ShichishitouDescription, // スキル説明 (七支刀)
        SilverBulletDescription, // スキル説明 (シルバーバレット)
        SkillDescription, // スキル説明 (SKILL)
        SkillMessage, // 共通 (スキル)
        SlipDamageMessage, // 共通 (スリップダメージ)
        SlipMessage, // 共通 (状態異常)
        SmokeBombDescription, // スキル説明 (発煙筒)
        StarShellDescription, // スキル説明 (照明弾)
        StringerMessage, // 敵行動 (毒針)
        SuffocationMessage, // スリップ (窒息)
        TaserGunDescription, // スキル説明 (テイザーガン)
        TryAttackMessage, // 共通 (攻撃後回避)
        UtsusemiDescription, // スキル説明 (空蝉)
        WabisukeDescription, // スキル説明 (侘助)
        WeakPointMessage, // 共通 (弱点)
        UtsusemiMessage, // 強化 (空蝉)
        MetronomeDescription, // スキル説明 (ゆびをふる)
        VerticalSelect, // 共通 (上下選択)
        VerticalSelectAndCancel, // 共通 (上下選択/キャンセル)
        HorizontalSelectAndCancel, // 共通 (左右選択/キャンセル)
        BattleContinue,
        BattleQuit,
        DefenceMessage,
    }
}